version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn app.main:app --reload --port=80 --host=0.0.0.0"
    image: germanevangelisti/nyc-taxi-prediction-services:latest
    ports:
      - 80:80
